# Generated by Django 4.2.11 on 2024-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_no',
        ),
        migrations.AddField(
            model_name='item',
            name='part_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='part_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_location',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
